# Scaffolding generated by Casein v5.1.1.5

module Casein
  class BlogpostsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Blogposts'
  		@blogposts = Blogpost.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View blogpost'
      @blogpost = Blogpost.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new blogpost'
    	@blogpost = Blogpost.new
    end

    def create
      @blogpost = Blogpost.new blogpost_params
    
      if @blogpost.save
        flash[:notice] = 'Blogpost created'
        redirect_to casein_blogposts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new blogpost'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update blogpost'
      
      @blogpost = Blogpost.find params[:id]
    
      if @blogpost.update_attributes blogpost_params
        flash[:notice] = 'Blogpost has been updated'
        redirect_to casein_blogposts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this blogpost'
        render :action => :show
      end
    end
 
    def destroy
      @blogpost = Blogpost.find params[:id]

      @blogpost.destroy
      flash[:notice] = 'Blogpost has been deleted'
      redirect_to casein_blogposts_path
    end
  
    private
      
      def blogpost_params
        params.require(:blogpost).permit(:title, :newpost)
      end

  end
end