# Scaffolding generated by Casein v5.1.1.5

module Casein
  class TourdatesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Tourdates'
  		@tourdates = Tourdate.order(sort_order(:venue)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View tourdate'
      @tourdate = Tourdate.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new tourdate'
    	@tourdate = Tourdate.new
    end

    def create
      @tourdate = Tourdate.new tourdate_params
    
      if @tourdate.save
        flash[:notice] = 'Tourdate created'
        redirect_to casein_tourdates_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new tourdate'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update tourdate'
      
      @tourdate = Tourdate.find params[:id]
    
      if @tourdate.update_attributes tourdate_params
        flash[:notice] = 'Tourdate has been updated'
        redirect_to casein_tourdates_path
      else
        flash.now[:warning] = 'There were problems when trying to update this tourdate'
        render :action => :show
      end
    end
 
    def destroy
      @tourdate = Tourdate.find params[:id]

      @tourdate.destroy
      flash[:notice] = 'Tourdate has been deleted'
      redirect_to casein_tourdates_path
    end
  
    private
      
      def tourdate_params
        params.require(:tourdate).permit(:venue, :lat, :long, :otherbands, :date)
      end

  end
end